### ISSUE TITLE
Unsupervised EDA with "conventional" methods

### ISSUE THREAD

**Issue by HssDix** [ArneSch/NF_Prj_MIMII_Dataset#12]
**Data input**

- [x] load data from pickle created by utility function

- [x] PSD-Data

- [ ] Mel-Filter-Data

- [ ] Beat-Data

**Scaling**

- [x] Log-Scaling

- [x] StandardScaling

**Dimensionality Reduction**

- [x] PCA including 2D/3D Visualization

**Clustering**

- [x] t-SNE for Visualization

- [x] K-Means

- [x] Mean-Shift

- [ ] DBSCAN

**Evaluation**

- [ ] Models that handle outlier like DBSCAN or those that calculate a certainty could be used as "prediction" model

**Comment by HssDix** [comment]
We should apply this notebook also for lower Signal to Noise ratios.

**Comment by ArneSch** [comment]
drop
