### ISSUE TITLE
Keep data at same place do not commit pkl

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#13]
Thisn might be to specific and should not have been commited:
A:\Dev\NF_Prj_MIMII_Dataset\sub_notebooks\clustering_EDA\data\pump_6dB_00020406_full_spectrum_128.pkl

My idea was to keep folder with extracted data with the maine dataset 
A:\Dev\NF_Prj_MIMII_Dataset\dataset\PSD_to_Pandas
including alwas the creation screept ...

lets discuss

**Comment by HssDix** [comment]
You're right. My bad, will fix it!

**Comment by HssDix** [comment]
resolved!
