### ISSUE TITLE
Audition Function Wishes and Bugs collection issue

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#17]
This issue acts as discussion collection card until split up into singel tasks:

bug: akku plot can not hue
bug: plot every 10th etc seems to go wrong 
bug: some times mel spectra turns into wrong time format ???

task: add ceptrum
task add MFCC

...

wish: combine PSD and PSD per file

wish: zoomable time series , zoomable other plots ..
wish: return all ax handles to use as pre nice plotting some time

**Comment by HssDix** [comment]
Idea: for space sake we could make the PSD and spectrum plot in (1, 2, x) subplot next to each other

**Comment by ArneSch** [comment]
drop
