### ISSUE TITLE
pipe is not creating a folder if the folder is not existing

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#31]
ileNotFoundError: [Errno 2] No such file or directory: '.\\pipes\\MEL_den_frame5_6dB_pump_ID00_20200504_132755.pkl'

some wehre here needs to be chack
![image](https://user-images.githubusercontent.com/61157316/80961967-5ed52480-8e0c-11ea-9840-8eb9671d1247.png)

this is good 
os.makedirs(target_folder_full, exist_ok=True)

**Comment by HssDix** [comment]
Resolved. Check latest commit.
