### ISSUE TITLE
README.md Review 

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#33]
I have made a base line of README.md please review
Then I think it would be good if the logo would be at the very top ...

**Comment by HssDix** [comment]
I did the review. Found some typos and changed not too much here and there. [Please take a look:](https://github.com/BA-HanseML/NF_Prj_MIMII_Dataset/edit/bendix_ensemble/README.md)

**Comment by ArneSch** [comment]
merged 👍
