### ISSUE TITLE
FUTURE WORK

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#43]
- [x] workflow_improvment.md - threading Jupyter file storing diagrams ... etc.
- [x] imporvments.md - list of left out tech like LSTM autoencoder, DOA filter.... just list .
- [x] application_notes.md - smart sensor train time reaction time sensor aligment etc ... training algorthems memory size ...

**Comment by ArneSch** [comment]
I think only thing that is open is the other modeling

**Comment by HssDix** [comment]
improvements.md updated with unsupervised and ensemble modeling.

I think workflow_improvements and application_notes are quite complete. So this issue can be closed right?
Reopen if there's still work to do.
