### ISSUE TITLE
Scpiy Sginal to env

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#5]
Scpiy is missing and I guess we eill needd the scipy.signal ata some point

**Comment by HssDix** [comment]
approved

- [x] add scipy to environment.yml
- [x] export environment_fullexport.yml

**Comment by ArneSch** [comment]
we need to do full export...

**Comment by ArneSch** [comment]
next time we merge to master this is solved fixed in thie commit:
https://github.com/ArneSch/NF_Prj_MIMII_Dataset/commit/bc8a544ab5f21ba877a27c425fa71cb60d07cf92
