### ISSUE TITLE
Main  Notebook

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#57]
make mockup notebook - ID04 and ID06
- [x] feat ext. design - mini EDA
- [x] feat ext. all ... (best feat. version exdia_v1_best_off)
- [x] ensamble  performace show of the best version
- [x] result summery

**Comment by ArneSch** [comment]
started in: https://github.com/BA-HanseML/NF_Prj_MIMII_Dataset/blob/Arne_pseudo_supervised/MIMII_main.ipynb

**Comment by HssDix** [comment]
current version: https://github.com/BA-HanseML/NF_Prj_MIMII_Dataset/blob/bendix_optimization/MIMII_main.ipynb

Ensemble is functional.
Results tbd.

**Comment by HssDix** [comment]
Results are generated. Some text and comments missing. Will add it!

**Comment by HssDix** [comment]
Everything done
