### ISSUE TITLE
Readme badges  !!

### ISSUE THREAD

**Issue by ArneSch** [ArneSch/NF_Prj_MIMII_Dataset#62]
https://www.freecodecamp.org/news/how-to-use-badges-to-stop-feeling-like-a-noob-d4e6600d37d2/

https://github.com/dwyl/repo-badges

https://github.com/badges/shields

**Comment by HssDix** [comment]
This is a good overview: https://shields.io/

Added:
1. license
2. contributors
3. contact info

**Comment by ArneSch** [comment]
proposal to add:
Version
![GitHub release (latest by date)](https://img.shields.io/github/v/release/BA-HanseML/NF_Prj_MIMII_Dataset)

issues open:
![GitHub issues](https://img.shields.io/github/issues/BA-HanseML/NF_Prj_MIMII_Dataset)

I was thinking about somthing that reads the yml export to display at least Py 3.7 and tensor flow etc ... but can not get this to work ... :(

**Comment by ArneSch** [comment]
Then as static seems also cool:
![pack](https://img.shields.io/badge/Python-3.7.6-green) ![pack](https://img.shields.io/badge/scikitlearn-0.22.2-blue) ![pack](https://img.shields.io/badge/Tensorflow-2.0.0-yellow)
![pack](https://img.shields.io/badge/jupyter-1.0.0-orange) ![pack](https://img.shields.io/badge/librosa-0.6.3-yellow)

**Comment by ArneSch** [comment]
![pack](https://img.shields.io/badge/anaconda-4.8.3-red)

**Comment by ArneSch** [comment]
Demo https://github.com/BA-HanseML/NF_Prj_MIMII_Dataset/tree/fe49302ec715a349860ac469d301e491a3d7d9d0

**Comment by HssDix** [comment]
Good addition! I am fine with the current status.
Close?

**Comment by ArneSch** [comment]
close
